<a href="https://colab.research.google.com/github/StephanyMejia25/datawarehouse-seguros/blob/main/notebooks/Corredores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

url = "https://raw.githubusercontent.com/StephanyMejia25/etl-data-pipeline/refs/heads/main/data/Raw/corredores.csv"

df = pd.read_csv(url)

df.head()

   id_corredor               nombre         zona    nivel  anios_experiencia
0            1    José López Flores  Paracentral      Mid                4.0
1            2    José Ortiz García     Centro     Junior                0.0
2            3   María Ramírez Cruz       Centro  SENIOR                 6.0
3            4  Fernanda Rojas Cruz          NaN  SENIOR                 8.0
4            5      Ana Gómez Rojas          NaN   Senior                4.0

In [2]:
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_corredor        80 non-null     int64
 1   nombre             80 non-null     object
 2   zona               63 non-null     object
 3   nivel              68 non-null     object
 4   anios_experiencia  76 non-null     float64
dtypes: float64(1), int64(1), object(3)
memory usage: 3.3+ KB

id_corredor           0
nombre                0
zona                 17
nivel                12
anios_experiencia     4
dtype: int64

In [3]:
corredores = df.copy()

corredores.columns = corredores.columns.str.strip().str.lower()

for col in corredores.select_dtypes(include='object').columns:
    corredores[col] = corredores[col].astype(str).str.strip()

corredores = corredores.replace(r'^\s*$', pd.NA, regex=True)

corredores = corredores.drop_duplicates()

# Display the first few rows and information about the cleaned DataFrame
display(corredores.head())
display(corredores.info())

   id_corredor               nombre         zona   nivel  anios_experiencia
0            1    José López Flores  Paracentral     Mid                4.0
1            2    José Ortiz García       Centro  Junior                0.0
2            3   María Ramírez Cruz       Centro  SENIOR                6.0
3            4  Fernanda Rojas Cruz          nan  SENIOR                8.0
4            5      Ana Gómez Rojas          nan  Senior                4.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_corredor        80 non-null     int64
 1   nombre             80 non-null     object
 2   zona               80 non-null     object
 3   nivel              80 non-null     object
 4   anios_experiencia  76 non-null     float64
dtypes: float64(1), int64(1), object(3)
memory usage: 3.3+ KB

None

In [4]:
validos_corredores = corredores[
    corredores['nombre'].notna() &
    corredores['anios_experiencia'].notna()
].copy()

rechazados_corredores = corredores[
    corredores['nombre'].isna() |
    corredores['anios_experiencia'].isna()
].copy()

print("Valid Corredores (first 5 rows):")
display(validos_corredores.head())
print("\nRejected Corredores (first 5 rows):")
display(rechazados_corredores.head())

print(f"\nNumber of valid corredores: {len(validos_corredores)}")
print(f"Number of rejected corredores: {len(rechazados_corredores)}")

Valid Corredores (first 5 rows):

   id_corredor               nombre         zona   nivel  anios_experiencia
0            1    José López Flores  Paracentral     Mid                4.0
1            2    José Ortiz García       Centro  Junior                0.0
2            3   María Ramírez Cruz       Centro  SENIOR                6.0
3            4  Fernanda Rojas Cruz          nan  SENIOR                8.0
4            5      Ana Gómez Rojas          nan  Senior                4.0

Rejected Corredores (first 5 rows):

    id_corredor                   nombre    zona   nivel  anios_experiencia
10           11      José Morales Flores     nan  junior                NaN
14           15      Fernanda Cruz Reyes  Centro     Mid                NaN
60           61    Carlos Torres Mendoza  Centro  junior                NaN
76           77  Valeria Vásquez Mendoza  Centro  junior                NaN

Number of valid corredores: 76
Number of rejected corredores: 4

In [5]:
def motivo_corredor(row):
    motivos = []

    if pd.isna(row['nombre']):
        motivos.append("nombre_vacio")

    if pd.isna(row['anios_experiencia']):
        motivos.append("anios_experiencia_vacio")

    return ",".join(motivos)

rechazados_corredores["motivo_rechazo"] = rechazados_corredores.apply(motivo_corredor, axis=1)
display(rechazados_corredores.head())

,id_corredor,nombre,zona,nivel,anios_experiencia,motivo_rechazo
10,11,José Morales Flores,nan,junior,NaN,anios_experiencia_vacio
14,15,Fernanda Cruz Reyes,Centro,Mid,NaN,anios_experiencia_vacio
60,61,Carlos Torres Mendoza,Centro,junior,NaN,anios_experiencia_vacio
76,77,Valeria Vásquez Mendoza,Centro,junior,NaN,anios_experiencia_vacio

In [6]:
validos_corredores.to_csv("corredores_curated.csv", index=False)

rechazados_corredores.to_csv("corredores_rejects.csv", index=False)

In [7]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 40.0 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [8]:
from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_user:zRyZICbHaRI4LPZUHN6kUrjYH63PhhaC@dpg-d6qu4s15pdvs73bhfcc0-a.oregon-postgres.render.com/etl_seguros_of05"

engine = create_engine(database_url)

try:
    test = pd.read_sql("SELECT 1", engine)
    print("Database connection successful!")
    print(test)
except Exception as e:
    print(f"Database connection failed: {e}")

Database connection successful!
   ?column?
0         1

In [9]:
# Save the validos_corredores DataFrame to the database
# Using if_exists='replace' will drop the table if it exists and recreate it.
# Use if_exists='append' to add rows to an existing table.
# Consider if_exists='fail' if you want to prevent overwriting existing tables.
validos_corredores.to_sql('corredores', engine, if_exists='replace', index=False)

print("validos_corredores data successfully uploaded to 'corredores' table.")

# Optional: Verify the data was uploaded by reading it back
# df_from_db = pd.read_sql('SELECT * FROM corredores', engine)
# display(df_from_db.head())

validos_corredores data successfully uploaded to 'corredores' table.

In [10]:
validos_corredores.to_sql(
    'corredores_curated',
    engine,
    if_exists='append',
    index=False
)

print("validos_corredores data successfully appended to 'corredores_curated' table.")

rechazados_corredores.to_sql(
    'corredores_rejects',
    engine,
    if_exists='append',
    index=False
)

print("rechazados_corredores data successfully appended to 'corredores_rejects' table.")

validos_corredores data successfully appended to 'corredores_curated' table.
rechazados_corredores data successfully appended to 'corredores_rejects' table.

In [11]:
pd.read_sql(
    "SELECT * FROM corredores_curated LIMIT 10",
    engine
)

   id_corredor                 nombre         zona   nivel  anios_experiencia
0            1      José López Flores  Paracentral     Mid                4.0
1            2      José Ortiz García       Centro  Junior                0.0
2            3     María Ramírez Cruz       Centro  SENIOR                6.0
3            4    Fernanda Rojas Cruz          nan  SENIOR                8.0
4            5        Ana Gómez Rojas          nan  Senior                4.0
5            6  Sofía Reyes Hernández    Occidente   Elite                3.0
6            7   Pedro Vásquez Torres        Costa     nan                1.0
7            8  Paula Ortiz Hernández       Centro  Junior               17.0
8            9  Carlos Torres Vásquez  Paracentral  junior                2.0
9           10     Juan Cruz Castillo    Occidente     nan                7.0