<a href="https://colab.research.google.com/github/StephanyMejia25/datawarehouse-seguros/blob/main/notebooks/siniestros.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

url = "https://raw.githubusercontent.com/StephanyMejia25/datawarehouse-seguros/refs/heads/main/data/siniestros.csv"

df = pd.read_csv(url)

df.head()

   id_siniestro  id_poliza fecha_siniestro monto_siniestro     estado
0             1      17400      16-10-2025         2092.59    ABIERTO
1             2       2465      01/08/2025        7,076.25    Abierto
2             3      15785      19-09-2025         702.27     cerrado
3             4      14299      27/09/2025         274.63     Abierto
4             5      12908      01/12/2025        9,377.69  Rechazado

In [2]:
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4620 entries, 0 to 4619
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_siniestro     4620 non-null   int64
 1   id_poliza        4620 non-null   int64
 2   fecha_siniestro  4620 non-null   object
 3   monto_siniestro  4004 non-null   object
 4   estado           3322 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.6+ KB

id_siniestro          0
id_poliza             0
fecha_siniestro       0
monto_siniestro     616
estado             1298
dtype: int64

In [3]:
siniestros_df = df.copy()

siniestros_df.columns = siniestros_df.columns.str.strip().str.lower()

for col in siniestros_df.select_dtypes(include='object').columns:
    siniestros_df[col] = siniestros_df[col].astype(str).str.strip()

siniestros_df = siniestros_df.replace(r'^\s*$', pd.NA, regex=True)

In [4]:
# Convert 'fecha_siniestro' to datetime
siniestros_df['fecha_siniestro'] = pd.to_datetime(siniestros_df['fecha_siniestro'], errors='coerce', dayfirst=True)

# Clean and convert 'monto_siniestro' to numeric
siniestros_df['monto_siniestro'] = siniestros_df['monto_siniestro'].astype(str).str.replace(',', '', regex=False)
siniestros_df['monto_siniestro'] = pd.to_numeric(siniestros_df['monto_siniestro'], errors='coerce')

# Normalize 'estado' column to lowercase
siniestros_df['estado'] = siniestros_df['estado'].str.lower()

siniestros_df = siniestros_df.drop_duplicates()

print("Info of the cleaned DataFrame:")
siniestros_df.info()
print("\nFirst 5 rows of the cleaned DataFrame:")
display(siniestros_df.head())

Info of the cleaned DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4620 entries, 0 to 4619
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_siniestro     4620 non-null   int64
 1   id_poliza        4620 non-null   int64
 2   fecha_siniestro  918 non-null    datetime64[ns]
 3   monto_siniestro  3677 non-null   float64
 4   estado           4620 non-null   object
dtypes: datetime64[ns](1), float64(1), int64(2), object(1)
memory usage: 180.6+ KB

First 5 rows of the cleaned DataFrame:

   id_siniestro  id_poliza fecha_siniestro  monto_siniestro     estado
0             1      17400      2025-10-16          2092.59    abierto
1             2       2465             NaT          7076.25    abierto
2             3      15785      2025-09-19           702.27    cerrado
3             4      14299             NaT           274.63    abierto
4             5      12908             NaT          9377.69  rechazado

In [5]:
validos_siniestros = siniestros_df[
    siniestros_df['fecha_siniestro'].notna() &
    siniestros_df['monto_siniestro'].notna()
].copy()

rechazados_siniestros = siniestros_df[
    siniestros_df['fecha_siniestro'].isna() |
    siniestros_df['monto_siniestro'].isna()
].copy()

print("Shape of validos_siniestros:", validos_siniestros.shape)
print("Shape of rechazados_siniestros:", rechazados_siniestros.shape)

print("\nFirst 5 rows of validos_siniestros:")
display(validos_siniestros.head())

print("\nFirst 5 rows of rechazados_siniestros:")
display(rechazados_siniestros.head())

Shape of validos_siniestros: (739, 5)
Shape of rechazados_siniestros: (3881, 5)

First 5 rows of validos_siniestros:

    id_siniestro  id_poliza fecha_siniestro  monto_siniestro     estado
0              1      17400      2025-10-16          2092.59    abierto
2              3      15785      2025-09-19           702.27    cerrado
7              8      23824      2025-01-17          2736.20    abierto
12            13       3716      2025-07-13         -4274.39  rechazado
23            24      17180      2025-06-13          6183.83    cerrado

First 5 rows of rechazados_siniestros:

   id_siniestro  id_poliza fecha_siniestro  monto_siniestro     estado
1             2       2465             NaT          7076.25    abierto
3             4      14299             NaT           274.63    abierto
4             5      12908             NaT          9377.69  rechazado
5             6       5107             NaT         10535.74        nan
6             7       3379             NaT         10513.30    abierto

In [6]:
def motivo_siniestro(row):
    motivos = []

    if pd.isna(row['fecha_siniestro']):
        motivos.append("fecha_siniestro_vacio")

    if pd.isna(row['monto_siniestro']):
        motivos.append("monto_siniestro_vacio")

    return ",".join(motivos)

rechazados_siniestros["motivo_rechazo"] = rechazados_siniestros.apply(motivo_siniestro, axis=1)

print("First 5 rows of rechazados_siniestros with rejection reasons:")
display(rechazados_siniestros.head())

First 5 rows of rechazados_siniestros with rejection reasons:

,id_siniestro,id_poliza,fecha_siniestro,monto_siniestro,estado,motivo_rechazo
1,2,2465,NaT,7076.25,abierto,fecha_siniestro_vacio
3,4,14299,NaT,274.63,abierto,fecha_siniestro_vacio
4,5,12908,NaT,9377.69,rechazado,fecha_siniestro_vacio
5,6,5107,NaT,10535.74,nan,fecha_siniestro_vacio
6,7,3379,NaT,10513.30,abierto,fecha_siniestro_vacio

In [7]:
validos_siniestros.to_csv("siniestros_curated.csv", index=False)
print("Saved validos_siniestros to siniestros_curated.csv")

rechazados_siniestros.to_csv("siniestros_rejects.csv", index=False)
print("Saved rechazados_siniestros to siniestros_rejects.csv")

Saved validos_siniestros to siniestros_curated.csv
Saved rechazados_siniestros to siniestros_rejects.csv

In [8]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 77.3 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [9]:
from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_user:zRyZICbHaRI4LPZUHN6kUrjYH63PhhaC@dpg-d6qu4s15pdvs73bhfcc0-a.oregon-postgres.render.com/etl_seguros_of05"
engine = create_engine(database_url)

# Define the table name for your siniestros data
table_name = 'siniestros'

# Upload the validos_siniestros DataFrame to the database
# Using if_exists='replace' will drop the table if it exists and recreate it
# Using index=False prevents writing the DataFrame index as a column in the SQL table
try:
    validos_siniestros.to_sql(table_name, engine, if_exists='replace', index=False)
    print(f"Successfully uploaded validos_siniestros to table '{table_name}'.")
except Exception as e:
    print(f"Error uploading data: {e}")

# Optional: Verify by reading a few rows back from the database
print(f"\nFirst 5 rows of '{table_name}' from the database:")
display(pd.read_sql(f"SELECT * FROM {table_name} LIMIT 5", engine))

Successfully uploaded validos_siniestros to table 'siniestros'.

First 5 rows of 'siniestros' from the database:

   id_siniestro  id_poliza fecha_siniestro  monto_siniestro     estado
0             1      17400      2025-10-16          2092.59    abierto
1             3      15785      2025-09-19           702.27    cerrado
2             8      23824      2025-01-17          2736.20    abierto
3            13       3716      2025-07-13         -4274.39  rechazado
4            24      17180      2025-06-13          6183.83    cerrado

In [10]:
try:
    validos_siniestros.to_sql('siniestros_curated', engine, if_exists='append', index=False)
    print("Successfully uploaded validos_siniestros to 'siniestros_curated'.")
except Exception as e:
    print(f"Error uploading validos_siniestros: {e}")

Successfully uploaded validos_siniestros to 'siniestros_curated'.

In [11]:
try:
    rechazados_siniestros.to_sql('siniestros_rejects', engine, if_exists='append', index=False)
    print("Successfully uploaded rechazados_siniestros to 'siniestros_rejects'.")
except Exception as e:
    print(f"Error uploading rechazados_siniestros: {e}")

Successfully uploaded rechazados_siniestros to 'siniestros_rejects'.

In [12]:
pd.read_sql(
"SELECT * FROM siniestros_curated LIMIT 10",
engine
)

   id_siniestro  id_poliza fecha_siniestro  monto_siniestro     estado
0             1      17400      2025-10-16          2092.59    abierto
1             3      15785      2025-09-19           702.27    cerrado
2             8      23824      2025-01-17          2736.20    abierto
3            13       3716      2025-07-13         -4274.39  rechazado
4            24      17180      2025-06-13          6183.83    cerrado
5            27      22625      2025-03-07           141.77        nan
6            33       2231      2025-09-21          2443.90  rechazado
7            36      16929      2025-01-06          3649.94    cerrado
8            45      15100      2025-01-27          8761.24    abierto
9            66      14064      2025-03-25          9842.05    abierto