<a href="https://colab.research.google.com/github/StephanyMejia25/datawarehouse-seguros/blob/main/notebooks/tipos_seguro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

url = "https://raw.githubusercontent.com/StephanyMejia25/datawarehouse-seguros/refs/heads/main/data/tipos_seguro.csv"

df = pd.read_csv(url)

df.head()

   id_tipo_seguro        tipo     categoria riesgo_base
0               1        Pyme      Familiar           -
1               2  Industrial   Empresarial       4.68
2               3  Industrial      Familiar        5.10
3               4  Industrial      Personal         NaN
4               5        Auto  empresarial         9.07

In [2]:
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_tipo_seguro  12 non-null     int64
 1   tipo            12 non-null     object
 2   categoria       10 non-null     object
 3   riesgo_base     10 non-null     object
dtypes: int64(1), object(3)
memory usage: 516.0+ bytes

id_tipo_seguro    0
tipo              0
categoria         2
riesgo_base       2
dtype: int64

In [3]:
tipos_seguro = df.copy()

tipos_seguro.columns = tipos_seguro.columns.str.strip().str.lower()

for col in tipos_seguro.select_dtypes(include='object').columns:
    tipos_seguro[col] = tipos_seguro[col].astype(str).str.strip()

tipos_seguro = tipos_seguro.replace(r'^\s*$', pd.NA, regex=True)

tipos_seguro = tipos_seguro.drop_duplicates()

display(tipos_seguro.head())
display(tipos_seguro.info())
display(tipos_seguro.isnull().sum())

   id_tipo_seguro        tipo    categoria riesgo_base
0               1        Pyme     Familiar           -
1               2  Industrial  Empresarial        4.68
2               3  Industrial     Familiar        5.10
3               4  Industrial     Personal         nan
4               5        Auto  empresarial        9.07

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_tipo_seguro  12 non-null     int64
 1   tipo            12 non-null     object
 2   categoria       12 non-null     object
 3   riesgo_base     12 non-null     object
dtypes: int64(1), object(3)
memory usage: 516.0+ bytes

None

id_tipo_seguro    0
tipo              0
categoria         0
riesgo_base       0
dtype: int64

In [4]:
missing_indicators = ['nan', '-']

validos_tipos_seguro = tipos_seguro[
    (~tipos_seguro['categoria'].isin(missing_indicators)) &
    (~tipos_seguro['riesgo_base'].isin(missing_indicators))
].copy()

rechazados_tipos_seguro = tipos_seguro[
    (tipos_seguro['categoria'].isin(missing_indicators)) |
    (tipos_seguro['riesgo_base'].isin(missing_indicators))
].copy()

display("Validos Tipos de Seguro (head):")
display(validos_tipos_seguro.head())
display("Rechazados Tipos de Seguro (head):")
display(rechazados_tipos_seguro.head())

'Validos Tipos de Seguro (head):'

   id_tipo_seguro        tipo    categoria riesgo_base
1               2  Industrial  Empresarial        4.68
2               3  Industrial     Familiar        5.10
4               5        Auto  empresarial        9.07
5               6  Industrial  Empresarial        2.52
6               7       Salud     Personal        0.92

'Rechazados Tipos de Seguro (head):'

    id_tipo_seguro        tipo categoria riesgo_base
0                1        Pyme  Familiar           -
3                4  Industrial  Personal         nan
8                9  Accidentes       nan        5.68
11              12    Agrícola       nan         nan

In [5]:
def motivo_tipos_seguro(row):
    motivos = []
    missing_indicators = ['nan', '-']

    if row['categoria'] in missing_indicators:
        motivos.append("categoria_vacia")

    if row['riesgo_base'] in missing_indicators:
        motivos.append("riesgo_base_vacio")

    return ",".join(motivos)

rechazados_tipos_seguro["motivo_rechazo"] = rechazados_tipos_seguro.apply(motivo_tipos_seguro, axis=1)
display(rechazados_tipos_seguro.head())

,id_tipo_seguro,tipo,categoria,riesgo_base,motivo_rechazo
0,1,Pyme,Familiar,-,riesgo_base_vacio
3,4,Industrial,Personal,nan,riesgo_base_vacio
8,9,Accidentes,nan,5.68,categoria_vacia
11,12,Agrícola,nan,nan,"categoria_vacia,riesgo_base_vacio"

In [6]:
validos_tipos_seguro.to_csv("tipos_seguro_validos.csv", index=False)

rechazados_tipos_seguro.to_csv("tipos_seguro_rechazados.csv", index=False)

In [7]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 32.4 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [8]:
from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_user:zRyZICbHaRI4LPZUHN6kUrjYH63PhhaC@dpg-d6qu4s15pdvs73bhfcc0-a.oregon-postgres.render.com/etl_seguros_of05"
engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)
print(test)

   ?column?
0         1

In [9]:
# Load validos_tipos_seguro to the database
validos_tipos_seguro.to_sql('tipos_seguro_validos', engine, if_exists='replace', index=False)
print("tipos_seguro_validos loaded successfully.")

# Load rechazados_tipos_seguro to the database
rechazados_tipos_seguro.to_sql('tipos_seguro_rechazados', engine, if_exists='replace', index=False)
print("tipos_seguro_rechazados loaded successfully.")

# You can verify by reading a sample from one of the tables
# verify_df = pd.read_sql('SELECT * FROM tipos_seguro_validos LIMIT 5', engine)
# print("\nVerified data from tipos_seguro_validos:")
# print(verify_df)

tipos_seguro_validos loaded successfully.
tipos_seguro_rechazados loaded successfully.

In [10]:
print("Appending validos_tipos_seguro to the database...")
validos_tipos_seguro.to_sql(
    'tipos_seguro_validos',
    engine,
    if_exists='append',
    index=False
)
print("Valid types of insurance appended successfully.")

print("Appending rechazados_tipos_seguro to the database...")
rechazados_tipos_seguro.to_sql(
    'tipos_seguro_rechazados',
    engine,
    if_exists='append',
    index=False
)
print("Rejected types of insurance appended successfully.")

# Optional: Verify by reading a sample from one of the tables
# verify_df_validos = pd.read_sql('SELECT * FROM tipos_seguro_validos ORDER BY id_tipo_seguro DESC LIMIT 5', engine)
# print("\nVerified appended data from tipos_seguro_validos:")
# print(verify_df_validos)

# verify_df_rechazados = pd.read_sql('SELECT * FROM tipos_seguro_rechazados ORDER BY id_tipo_seguro DESC LIMIT 5', engine)
# print("\nVerified appended data from tipos_seguro_rechazados:")
# print(verify_df_rechazados)

Appending validos_tipos_seguro to the database...
Valid types of insurance appended successfully.
Appending rechazados_tipos_seguro to the database...
Rejected types of insurance appended successfully.

In [11]:
df_verify_validos = pd.read_sql(
    "SELECT * FROM tipos_seguro_validos LIMIT 10",
    engine
)
display(df_verify_validos)

   id_tipo_seguro        tipo    categoria riesgo_base
0               2  Industrial  Empresarial        4.68
1               3  Industrial     Familiar        5.10
2               5        Auto  empresarial        9.07
3               6  Industrial  Empresarial        2.52
4               7       Salud     Personal        0.92
5               8   Educación  empresarial        7.42
6              10      Dental     Especial        2.70
7              11        Auto  empresarial        4.33
8               2  Industrial  Empresarial        4.68
9               3  Industrial     Familiar        5.10